#! /bin/sh
#  /etc/init.d/AutomationServerService 

### BEGIN INIT INFO
# Provides:          AutomationServerService
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6
# Short-Description: Starts the AutomationServerService service
# Description:       This file is used to start the daemon
#                    and should be placed in /etc/init.d
### END INIT INFO

# Author:   F Guiet
# Url:      
# Date:     26/03/2016

NAME="AutomationServer"
DESC="AutomationServer service"

EXEC="/usr/bin/jsvc"
#USER="root"
HOME_PATH="/home/fred/AutomationServer"
PID="${HOME_PATH}/$NAME.pid"
LOG4J="log4j.configuration=file:${HOME_PATH}/config/log4j.xml"
JAVA_HOME="/usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt"
JAVA_LIBRARY_PATH="java.library.path=/home/fred/AutomationServer/lib"
CLASS_PATH="${HOME_PATH}/lib/*:${HOME_PATH}/AutomationServer.jar"
ARGS="-DSaveToInfluxDB=FALSE"
LOG_OUT="${HOME_PATH}/log/${NAME}.out"
LOG_ERR="${HOME_PATH}/log/${NAME}.err"
PID="${HOME_PATH}/${NAME}.pid"
CLASS=fr.guiet.automationserver.AutomationServer
export LANG=fr_FR.UTF-8

jsvc_exec()
{   
    #cd $HOME_PATH
    sudo rm /var/lock/LCK..ttyUSB0
    sudo $EXEC -home "$JAVA_HOME" -cp "$CLASS_PATH" -D"${JAVA_LIBRARY_PATH}" -D"${LOG4J}" $ARGS -outfile $LOG_OUT -errfile $LOG_ERR -pidfile "$PID" $1 $CLASS  
}

case "$1" in
    start)  
        echo "Starting the $DESC..."        
        
        # Start the service
        jsvc_exec
        
        echo "The $DESC has started."
    ;;
    stop)
        echo "Stopping the $DESC..."
        
        # Stop the service
        jsvc_exec "-stop"       
        
        echo "The $DESC has stopped."
    ;;
    restart)
        if [ -f "$PID" ]; then
            
            echo "Restarting the $DESC..."
            
            # Stop the service
            jsvc_exec "-stop"
            
            # Start the service
            jsvc_exec
            
            echo "The $DESC has restarted."
        else
            echo "Daemon not running, no action taken"
            exit 1
        fi
            ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 3
    ;;
esac
