apiVersion: v1
kind: PersistentVolume
metadata:
   name: grafana-nfs-pv
   labels:
      #TODO: type loca?? what does it mean?
      type: local
spec:
   storageClassName: grafana-nfs-pv
   capacity:
      #Sets here the max capacity
      storage: 10Mi
   accessModes:
     - ReadWriteOnce
   nfs:
      server: nfs.guiet.lan
      path: "/mnt/touros-ext-drive/k8s-data/grafana-pv" 
      
      
   