apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-nfs-pvc
spec:
  accessModes:
    #Only one pod can read or write? need to be check
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  #Used to bound pvc and pv
  storageClassName: openhab-nfs-pv