#!/bin/bash

#create volume bind with docker container
mkdir -p /home/fred/applications/node-red/data

#node-red is launch with pirate user (uid=1000)
#folder is owned by fred user
chmod o+rwx /home/fred/applications/node-red/data

