#!/bin/bash

#add fred group
#sudo groupadd fred --gid 1001
#add fred user
#sudo useradd -r -s /sbin/nologin fred --uid 1001 -g fred

#create volume bind with docker container
sudo mkdir -p /home/fred/applications/automationserver
sudo mkdir -p /home/fred/applications/automationserver/config
sudo mkdir -p  /home/fred/applications/automationserver/logs
sudo mkdir -p  /home/fred/applications/automationserver/bin
sudo mkdir -p  /home/fred/applications/automationserver/cmd

#add conf file
sudo cp  /home/fred/git/AutomationServer/third-party-tools/automationserver/conf/*.properties /home/fred/applications/automationserver/config 
sudo cp /home/fred/git/AutomationServer/third-party-tools/automationserver/conf/*.xml /home/fred/applications/automationserver/config
sudo cp /home/fred/git/AutomationServer/third-party-tools/automationserver/conf/gammu-config /home/fred/applications/automationserver/config
sudo cp /home/fred/git/AutomationServer/third-party-tools/automationserver/cmd/* /home/fred/applications/automationserver/cmd/

#change applications/automationserver folders owner
#sudo chown -R fred:fred /home/fred/applications/automationserver
